# Winch Control System Configuration File
# This is an INI-format configuration file

# シリアルポート設定
[Serial]
port = /dev/ttyUSB0

# UDP設定
[UDP]
port = 5005

# CAN設定
[CAN]
interface = can0

# コントローラー設定
[Controller]
device = /dev/input/by-id/usb-Logicool_Gamepad_F310_F9BC2D6C-event-joystick
max_velocity = 5
deadzone = 0.05
low_gain = 0.3
high_gain = 2.0

# PD制御パラメータ
[PDControl]

# モータ1 ver
#motor1_kp = 10.0
motor1_kp = 0.0
motor1_kd = 0.01

# モータ2 hori
#motor2_kp = 0.0
motor2_kp = 0.2
motor2_kd = 0.002

# 補償する重力値 [単位: kg]
gravity_compensation_kg = 0.55

# ポテンショメータ
[Potentiometer]

# ポテンショメータ0のオフセット値[単位: degrees]
offset0 = 86.9455
offset1 = 52.8

# フラグ設定
[Flags]
enable_serial = true
enable_udp = true
enable_can = true
enable_can_controller = false
move_motors = false
output_csv = true

# CSV出力先設定
[CSV]
output_directory = ./data_logs
